# Generated by Django 4.2.3 on 2025-01-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyData",
            fields=[
                (
                    "establishment_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("establishment_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trrn", models.BigIntegerField()),
                ("date_of_credit", models.DateTimeField()),
                ("amount", models.IntegerField()),
                ("wage_month", models.CharField(max_length=50)),
                ("no_of_employee", models.IntegerField()),
                ("ecr", models.CharField(max_length=10)),
            ],
        ),
    ]
